# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LoginInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, email: str=None, password: str=None):  # noqa: E501
        """LoginInfo - a model defined in Swagger

        :param email: The email of this LoginInfo.  # noqa: E501
        :type email: str
        :param password: The password of this LoginInfo.  # noqa: E501
        :type password: str
        """
        self.swagger_types = {
            'email': str,
            'password': str
        }

        self.attribute_map = {
            'email': 'email',
            'password': 'password'
        }
        self._email = email
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'LoginInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The login_info of this LoginInfo.  # noqa: E501
        :rtype: LoginInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self) -> str:
        """Gets the email of this LoginInfo.


        :return: The email of this LoginInfo.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this LoginInfo.


        :param email: The email of this LoginInfo.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    # @property
    # def user_name(self) -> str:
    #     """Gets the user_name of this LoginInfo.


    #     :return: The user_name of this LoginInfo.
    #     :rtype: str
    #     """
    #     return self._user_name

    # @user_name.setter
    # def user_name(self, user_name: str):
    #     """Sets the user_name of this LoginInfo.


    #     :param user_name: The user_name of this LoginInfo.
    #     :type user_name: str
    #     """
    #     if user_name is None:
    #         raise ValueError("Invalid value for `user_name`, must not be `None`")  # noqa: E501

    #     self._user_name = user_name

    @property
    def password(self) -> str:
        """Gets the password of this LoginInfo.


        :return: The password of this LoginInfo.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this LoginInfo.


        :param password: The password of this LoginInfo.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password
